### ISSUE TITLE
301 not being followed to Vecnet cache of solr

### ISSUE THREAD

**Issue by stevenvandervalk** [vecnet/deploy-dl#4]
Seeing 

`failed: [192.168.33.13] => {"dest": "/opt/pkg/solr-4.10.2.tgz", "failed": true, "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "http://dl.vecnet.org/i/solr-4.10.2.tgz"}
msg: Request failed`

after : 
`vagrant up sa`
`make local standalone deploy`

**Comment by stevenvandervalk** [comment]
I used the old `solr_cache_url` but then the next download was a vecnet url as well.  So is it just me experiencing that outside your lan/firewall?

**Comment by dbrower** [comment]
this is my mistake. I was caching those images on the dl server, but when I redeployed it, the route disappeared from the nginx config. I will add it back.

**Comment by dbrower** [comment]
This is because the dl production server is slightly different from the standalone server, which is what I ended up using to get the deploy done. I will add the role to set the file cache up to the standalone playbook.
